import PizzaImage from "@/assets/pizza-main (1).png";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Image from "next/image";
import ProductCard, { Product } from "./components/Product-Card";

const products: Product[] = [
  {
    id: "1",
    name: "Margarita Pizza",
    description: "This is a very tasty pizza",
    image: "/pizza-main.png",
    price: 500,
  },
  {
    id: "2",
    name: "Margarita Pizza",
    description: "This is a very tasty pizza",
    image: "/pizza-main.png",
    price: 500,
  },
  {
    id: "3",
    name: "Margarita Pizza",
    description: "This is a very tasty pizza",
    image: "/pizza-main.png",
    price: 500,
  },
  {
    id: "4",
    name: "Margarita Pizza",
    description: "This is a very tasty pizza",
    image: "/pizza-main.png",
    price: 500,
  },
  {
    id: "5",
    name: "Margarita Pizza",
    description: "This is a very tasty pizza",
    image: "/pizza-main.png",
    price: 500,
  },
];

export default function Home() {
  return (
    <>
      <section className="bg-white">
        <div className="container py-24 flex gap-2">
          <div>
            <h1 className="text-7xl font-black font-sans leading-2">
              Super Delicious Pizza in <br />
              <span className="text-primary">Only 45 Minutes!</span>
            </h1>
            <p className="text-2xl mt-8 max-w-lg leading-snug">
              Enjoy a Free Meal if Your Order Takes More Than 45 Minutes!
            </p>
            <Button className="mt-8 text-lg rounded-full py-7 px-6 font-bold">
              Get your pizza now
            </Button>
          </div>
          <div>
            <Image alt="pizza-main" src={PizzaImage} width={400} height={400} />
          </div>
        </div>
      </section>

      <section className="mt-5" >
        <div className="container">
          <Tabs defaultValue="pizza">
            <TabsList>
              <TabsTrigger className="text-md" value="pizza">
                Pizza
              </TabsTrigger>
              <TabsTrigger className="text-md" value="beverages">
                Beverages
              </TabsTrigger>
            </TabsList>
            <TabsContent value="pizza">
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6 mt-6">
                {products.map((product) => (
                  <ProductCard product={product} key={product.id} />
                ))}
              </div>
            </TabsContent>
            <TabsContent value="beverages">
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6 mt-6">
                {products.map((product) => (
                  <ProductCard product={product} key={product.id} />
                ))}
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </section>
    </>
  );
}

// how we apply theme by using shadcn in your priject

// go to theme section choose the theme colour and get the code by click copy code and the paste it in you global.css

// how we apply the font in outr project by usig next js

// so first select the fontstyle and changing in layout.tsx

// // like this
// import type { Metadata } from "next";
// import { Manrope } from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";
// const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={cn(
//           "min-h-screen bg-background font-manrope antialiased",
//           manrope.variable
//         )}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// in this we used the manrope and paste the variable from shadcn installation section

// and the third step is this go to the tylwind.config.ts file and in extend section paste your font here

//  extend: {
// fontFamily: {
//   manrope: ["var(--font-manrope)", ...fontFamily.sans],
// },

// like this  now after this your font and theme is applied in your project

// if you change the theme colour you can go the global,css file and root folder in first line change you colour
